apiVersion: batch/v1
kind: Job
metadata:
  name: translator-service
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: translator-service
          image: leeflangjs/translator-service:latest
          env:
            - name: kafka.host
              value:
            - name: kafka.topic
              value: 
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
