apiVersion: batch/v1
kind: Job
metadata:
  name: naturalis-api-translator
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: naturalis-api-translator
          image: leeflangjs/naturalis-api-translator:latest
          env:
            - name: kafka.host
              value:
            - name: kafka.topic
              value: 
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
