apiVersion: batch/v1
kind: Job
metadata:
  name: naturalis-api-translator
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: naturalis-api-translator
          image: leeflangjs/naturalis-api-translator:latest
          env:
            - name: kafka.host
              value: kafka-test-0.kafka-test-headless.default.svc.cluster.local:9092
            - name: kafka.topic
              value: naturalis
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
